setup-iptables: feat: Set up defensive interpreter behaviors and unhandled error managing
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>

diff --git a/setup-iptables b/setup-iptables
--- a/setup-iptables
+++ b/setup-iptables
@@ -1,6 +1,33 @@
 #!/usr/bin/env bash
 # Setup iptables firewall rules to forward packets through the redsocks service
 
+printf \
+    'Info: Configuring the defensive interpreter behaviors...\n'
+set_opts=(
+    # Terminate script execution when an unhandled error occurs
+    -o errexit
+    -o errtrace
+
+    # Terminate script execution when an unset parameter variable is
+    # referenced
+    -o nounset
+)
+if ! set "${set_opts[@]}"; then
+    printf \
+        'Error: Unable to configure the defensive interpreter behaviors.\n' \
+        1>&2
+    exit 1
+fi
+
+printf \
+    'Info: Setting the ERR trap...\n'
+if ! trap 'printf "Error: The program has encountered an unhandled error and is prematurely aborted.\\n" 1>&2' ERR; then
+    printf \
+        'Error: Unable to set the ERR trap.\n' \
+        1>&2
+    exit 1
+fi
+
 # Create new chain
 iptables -t nat -N REDSOCKS
 
